import{productPostInterface, productGetInterface, productToEditInterface, productToShowInterface} from './types';

export const productPostInitial:productPostInterface = {
    sku: "",
    productType: "",
    productName: "",
    productDescription: "",
    productPrice: "",
    productOldPrice: "",
    productStock: "",
    productRate: "",
    reviewQuantity: "",
    soldQuantity: "",
    productViews: "",
    sizeOne: "",
    sizeTwo: "",
    sizeThree: "",
    sizeFour: "",
    sizeFive: "",
    productImage: "",
    productThumbnail: "",
    categoryOne: "",
    categoryTwo: "",
    categoryThree: "",
    categoryFour: "",
    categoryFive: "",
    interestForYou: "",
    productProfit: ""
  }

  export const productGetInitial:productGetInterface = {
    sku: "",
    productType: "",
    productName: "",
    productDescription: "",
    productPrice: 0,
    productOldPrice: 0,
    productStock: 0,
    productRate: 0,
    reviewQuantity: 0,
    soldQuantity: 0,
    productViews: 0,
    sizeOne: "",
    sizeTwo: "",
    sizeThree: "",
    sizeFour: "",
    sizeFive: "",
    productImage: "",
    productThumbnail: "",
    categoryOne: "",
    categoryTwo: "",
    categoryThree: "",
    categoryFour: "",
    categoryFive: "",
    interestForYou: "",
    productProfit: 0
  }

  export const productToEditInitial:productToEditInterface = {
    sku: "",
    productType: "",
    productName: "",
    productDescription: "",
    productPrice: 0,
    productOldPrice: 0,
    productStock: 0,
    productRate: 0,
    reviewQuantity: 0,
    soldQuantity: 0,
    productViews: 0,
    sizeOne: "",
    sizeTwo: "",
    sizeThree: "",
    sizeFour: "",
    sizeFive: "",
    productImage: "",
    productThumbnail: "",
    categoryOne: "",
    categoryTwo: "",
    categoryThree: "",
    categoryFour: "",
    categoryFive: "",
    interestForYou: "",
    productProfit: 0
  }

  export const productToShowInitial:productToShowInterface = {
    sku: "",
    productType: "",
    productName: "",
    productDescription: "",
    productPrice: 0,
    productOldPrice: 0,
    productStock: 0,
    productRate: 0,
    reviewQuantity: 0,
    soldQuantity: 0,
    productViews: 0,
    sizeOne: "",
    sizeTwo: "",
    sizeThree: "",
    sizeFour: "",
    sizeFive: "",
    productImage: "",
    productThumbnail: "",
    categoryOne: "",
    categoryTwo: "",
    categoryThree: "",
    categoryFour: "",
    categoryFive: "",
    interestForYou: "",
    productProfit: 0
  }